# Generated by Django 2.2.6 on 2019-10-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to=None),
            preserve_default=False,
        ),
    ]
